#Steam Gaming Mode Gamescope Overlay

[preset 3]
control=mangohud
legacy_layout=true
background_alpha=0.6
round_corners=10
background_color=000000

font_size=24
text_color=FFFFFF
position=centered

pci_dev=0:01:00.0
table_columns=3
text_color=FFFFFF

custom_text=AMD BC-250

#GPU Usage
gpu_color=f26522
gpu_text=RDNA2
gpu_stats
gpu_core_clock
gpu_mem_clock
gpu_temp
#gpu_power

#CPU Usage
cpu_color=ed1c24
cpu_text=Zen2
cpu_stats
cpu_mhz
cpu_temp
#cpu_power

#Memory Usage
custom_text=16GB GDDR6
vram_color=f26522
vram

ram_color=ed1c24
ram

#Framerate Usage
fps
engine_short_names
engine_color=FFFFFF

frame_timing
frametime_color=FFFFFF

# APU Power
custom_text=APU Power:
exec=bash -c "GPU_HWMON=\$(dirname \$(grep -l amdgpu /sys/class/hwmon/hwmon*/name)); read v < \$GPU_HWMON/power1_average; printf '%s W\n' \"\$((v/1000000)).\$((v%1000000/100000))\""

# APU Core Voltage
custom_text=APU mV:
exec=bash -c "GPU_HWMON=\$(dirname \$(grep -l -i amdgpu /sys/class/hwmon/hwmon*/name)); read v < \$GPU_HWMON/in0_input; printf '%s mV\n' \$v"

# CPU Core Voltage
custom_text=CPU mV:
exec=bash -c "GPU_HWMON=\$(dirname \$(grep -l -i amdgpu /sys/class/hwmon/hwmon*/name)); read v < \$GPU_HWMON/in1_input; printf '%s mV\n' \$v"

# APU Fan RPM
custom_text=APU Fan:
exec=bash -c "FAN_HWMON=\$(dirname \$(grep -l -i nct /sys/class/hwmon/hwmon*/name)); read v < \$FAN_HWMON/fan2_input; printf '%s RPM\n' \$v"